// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.1
// source: pb/proto/doc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMD int32

const (
	CMD_CMDNONE  CMD = 0   //空
	CMD_LOGIN    CMD = 1   //登录命令
	CMD_MAIN     CMD = 2   //主命令
	CMD_INNER    CMD = 200 //服务器内部消息命令
	CMD_CLIENT   CMD = 201 //客户端内部消息命令
	CMD_PVP      CMD = 3   //战斗
	CMD_NOTIFY   CMD = 4   //通知
	CMD_MATCHING CMD = 5   //匹配
	CMD_AUTH     CMD = 6   //登录认证服命令
	CMD_PAYMENT  CMD = 7   //充值服命令
	CMD_PACK     CMD = 8   //道具背包
)

// Enum value maps for CMD.
var (
	CMD_name = map[int32]string{
		0:   "CMDNONE",
		1:   "LOGIN",
		2:   "MAIN",
		200: "INNER",
		201: "CLIENT",
		3:   "PVP",
		4:   "NOTIFY",
		5:   "MATCHING",
		6:   "AUTH",
		7:   "PAYMENT",
		8:   "PACK",
	}
	CMD_value = map[string]int32{
		"CMDNONE":  0,
		"LOGIN":    1,
		"MAIN":     2,
		"INNER":    200,
		"CLIENT":   201,
		"PVP":      3,
		"NOTIFY":   4,
		"MATCHING": 5,
		"AUTH":     6,
		"PAYMENT":  7,
		"PACK":     8,
	}
)

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}

func (x CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_doc_proto_enumTypes[0].Descriptor()
}

func (CMD) Type() protoreflect.EnumType {
	return &file_pb_proto_doc_proto_enumTypes[0]
}

func (x CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD.Descriptor instead.
func (CMD) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_doc_proto_rawDescGZIP(), []int{0}
}

type ACT int32

const (
	ACT_CMDNONE_NONE ACT = 0 //空
	// -------------------------------------------内网服消息开始----------------------------------------------------
	ACT_INNER_SERVERINFO ACT = 1 //服务器启动
	ACT_INNER_RPCFORWARD ACT = 2 //内网消息重定向
	ACT_INNER_GMCMD      ACT = 3 //GM命令
)

// Enum value maps for ACT.
var (
	ACT_name = map[int32]string{
		0: "CMDNONE_NONE",
		1: "INNER_SERVERINFO",
		2: "INNER_RPCFORWARD",
		3: "INNER_GMCMD",
	}
	ACT_value = map[string]int32{
		"CMDNONE_NONE":     0,
		"INNER_SERVERINFO": 1,
		"INNER_RPCFORWARD": 2,
		"INNER_GMCMD":      3,
	}
)

func (x ACT) Enum() *ACT {
	p := new(ACT)
	*p = x
	return p
}

func (x ACT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACT) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_doc_proto_enumTypes[1].Descriptor()
}

func (ACT) Type() protoreflect.EnumType {
	return &file_pb_proto_doc_proto_enumTypes[1]
}

func (x ACT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACT.Descriptor instead.
func (ACT) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_doc_proto_rawDescGZIP(), []int{1}
}

type ERROR int32

const (
	ERROR_SUCCESS ERROR = 0 // 成功
	ERROR_FAIL    ERROR = 1 // 失败
)

// Enum value maps for ERROR.
var (
	ERROR_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
	}
	ERROR_value = map[string]int32{
		"SUCCESS": 0,
		"FAIL":    1,
	}
)

func (x ERROR) Enum() *ERROR {
	p := new(ERROR)
	*p = x
	return p
}

func (x ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_doc_proto_enumTypes[2].Descriptor()
}

func (ERROR) Type() protoreflect.EnumType {
	return &file_pb_proto_doc_proto_enumTypes[2]
}

func (x ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERROR.Descriptor instead.
func (ERROR) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_doc_proto_rawDescGZIP(), []int{2}
}

type MyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestData string `protobuf:"bytes,1,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"`
}

func (x *MyRequest) Reset() {
	*x = MyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_doc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyRequest) ProtoMessage() {}

func (x *MyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_doc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyRequest.ProtoReflect.Descriptor instead.
func (*MyRequest) Descriptor() ([]byte, []int) {
	return file_pb_proto_doc_proto_rawDescGZIP(), []int{0}
}

func (x *MyRequest) GetRequestData() string {
	if x != nil {
		return x.RequestData
	}
	return ""
}

type MyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseData string `protobuf:"bytes,1,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`
}

func (x *MyResponse) Reset() {
	*x = MyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_doc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyResponse) ProtoMessage() {}

func (x *MyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_doc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyResponse.ProtoReflect.Descriptor instead.
func (*MyResponse) Descriptor() ([]byte, []int) {
	return file_pb_proto_doc_proto_rawDescGZIP(), []int{1}
}

func (x *MyResponse) GetResponseData() string {
	if x != nil {
		return x.ResponseData
	}
	return ""
}

type InnerNotfiyEmailData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` //服务器名称
	Ips  []string `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`   //ip数据
	Data string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` //信息
	Dt   string   `protobuf:"bytes,4,opt,name=dt,proto3" json:"dt,omitempty"`     //日期时间
}

func (x *InnerNotfiyEmailData) Reset() {
	*x = InnerNotfiyEmailData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_doc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerNotfiyEmailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerNotfiyEmailData) ProtoMessage() {}

func (x *InnerNotfiyEmailData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_doc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerNotfiyEmailData.ProtoReflect.Descriptor instead.
func (*InnerNotfiyEmailData) Descriptor() ([]byte, []int) {
	return file_pb_proto_doc_proto_rawDescGZIP(), []int{2}
}

func (x *InnerNotfiyEmailData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InnerNotfiyEmailData) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *InnerNotfiyEmailData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *InnerNotfiyEmailData) GetDt() string {
	if x != nil {
		return x.Dt
	}
	return ""
}

var File_pb_proto_doc_proto protoreflect.FileDescriptor

var file_pb_proto_doc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x6f, 0x63, 0x22, 0x2e, 0x0a, 0x09, 0x4d, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x0a, 0x4d, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x60, 0x0a, 0x14,
	0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x66, 0x69, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x64, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x74, 0x2a, 0x84,
	0x01, 0x0a, 0x03, 0x43, 0x4d, 0x44, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4d, 0x44, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x4d, 0x41, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x05, 0x49, 0x4e, 0x4e, 0x45,
	0x52, 0x10, 0xc8, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0xc9,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x56, 0x50, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f,
	0x54, 0x49, 0x46, 0x59, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x49,
	0x4e, 0x47, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x55, 0x54, 0x48, 0x10, 0x06, 0x12, 0x0b,
	0x0a, 0x07, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x41, 0x43, 0x4b, 0x10, 0x08, 0x2a, 0x54, 0x0a, 0x03, 0x41, 0x43, 0x54, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x4d, 0x44, 0x4e, 0x4f, 0x4e, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x49, 0x4e,
	0x46, 0x4f, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x5f, 0x52, 0x50,
	0x43, 0x46, 0x4f, 0x52, 0x57, 0x41, 0x52, 0x44, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e,
	0x4e, 0x45, 0x52, 0x5f, 0x47, 0x4d, 0x43, 0x4d, 0x44, 0x10, 0x03, 0x2a, 0x1e, 0x0a, 0x05, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x32, 0x38, 0x0a, 0x09, 0x4d,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x4d, 0x79, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x0e, 0x2e, 0x64, 0x6f, 0x63, 0x2e, 0x4d, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x64, 0x6f, 0x63, 0x2e, 0x4d, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_proto_doc_proto_rawDescOnce sync.Once
	file_pb_proto_doc_proto_rawDescData = file_pb_proto_doc_proto_rawDesc
)

func file_pb_proto_doc_proto_rawDescGZIP() []byte {
	file_pb_proto_doc_proto_rawDescOnce.Do(func() {
		file_pb_proto_doc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_doc_proto_rawDescData)
	})
	return file_pb_proto_doc_proto_rawDescData
}

var file_pb_proto_doc_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_proto_doc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_proto_doc_proto_goTypes = []interface{}{
	(CMD)(0),                     // 0: doc.CMD
	(ACT)(0),                     // 1: doc.ACT
	(ERROR)(0),                   // 2: doc.ERROR
	(*MyRequest)(nil),            // 3: doc.MyRequest
	(*MyResponse)(nil),           // 4: doc.MyResponse
	(*InnerNotfiyEmailData)(nil), // 5: doc.InnerNotfiyEmailData
}
var file_pb_proto_doc_proto_depIdxs = []int32{
	3, // 0: doc.MyService.MyMethod:input_type -> doc.MyRequest
	4, // 1: doc.MyService.MyMethod:output_type -> doc.MyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_proto_doc_proto_init() }
func file_pb_proto_doc_proto_init() {
	if File_pb_proto_doc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_doc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_doc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_doc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerNotfiyEmailData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_doc_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_proto_doc_proto_goTypes,
		DependencyIndexes: file_pb_proto_doc_proto_depIdxs,
		EnumInfos:         file_pb_proto_doc_proto_enumTypes,
		MessageInfos:      file_pb_proto_doc_proto_msgTypes,
	}.Build()
	File_pb_proto_doc_proto = out.File
	file_pb_proto_doc_proto_rawDesc = nil
	file_pb_proto_doc_proto_goTypes = nil
	file_pb_proto_doc_proto_depIdxs = nil
}
